image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - main
  before_script:
    - docker login registry.gitlab.com -u bianca.mustea -p jG-zxC9mbWkyCVfAjU_K
  script:    
    - docker build -t registry.gitlab.com/bianca.mustea/proiect-sincretic-2024/turnurile_hanoi:latest .    
    - docker push registry.gitlab.com/bianca.mustea/proiect-sincretic-2024/turnurile_hanoi:latest    
  after_script:
    - docker logout bianca.mustea
  stage: build
