image: docker:stable

services:
  - name: docker:dind
    command: ["--privileged"]

variables:
  DOCKER_TLS_CERTDIR: ""
  CI_REGISTRY_IMAGE: "registry.gitlab.com/bianca.mustea/proiect-sincretic-2024/turnuri_hanoi"
  CI_REGISTRY: "registry.gitlab.com"

stages:
  - build

build:
  stage: build
  only:
    - main
  before_script:
    - docker login $CI_REGISTRY
  script:    
    - docker build -t $CI_REGISTRY_IMAGE:latest .    
    - docker push $CI_REGISTRY_IMAGE:latest    
  after_script:
    - docker logout $CI_REGISTRY
