stages:
  - build_and_publish

variables:
  IMAGE_TAG: "registry.gitlab.com/bianca.mustea/proiect-sincretic-2024"

build_and_publish:
  stage: build_and_publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login ghcr.io -u bianca.mustea --password-stdin
    - docker build . -t $IMAGE_TAG
    - docker push $IMAGE_TAG
  only:
    - main
