image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - main
  before_script:
    - docker login -u immbianca -p ${CI_REGISTRY_PASSWORD}
  script:    
    - docker build -t immbianca/turnuri_hanoi:latest .    
    - docker push immbianca/turnuri_hanoi:latest    
  after_script:
    - docker logout ${CI_REGISTRY}
  stage: build
