image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - main
  before_script:
    - docker login gitlab.upt.ro -u bianca.mustea -p ${CI_REGISTRY_PASSWORD}
  script:    
    - docker build -t gitlab.upt.ro/bianca.mustea/proiect-sincretic-2024:latest .    
    - docker push gitlab.upt.ro/bianca.mustea/proiect-sincretic-2024:latest    
  after_script:
    - docker logout ${CI_REGISTRY}
  stage: build
