image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

build:
  only:
    - main
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:    
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .    
    - docker push ${CI_REGISTRY_IMAGE}:latest    
  after_script:
    - docker logout ${CI_REGISTRY}
  stage: build
